In [1]:
# importing the now modularized machine learning process for integration
from absenteeism_module import *

# using model on a fresh, unseen data data set
# instantiating model class
model = absenteeism_model('model', 'scaler')

# cleaning new data using custom method
model.load_and_clean_data('Absenteeism_new_data.csv')

# displaying predictions. The prediction feature is the final conclusion. 
# If below 50% probability, the result is zero
# Above 50% probability is 1
model.predicted_outputs()

/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.873392,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.268305,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.196385,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.723502,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.716891,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.570524,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.134118,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.525007,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.454998,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.351108,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.096533,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.189479,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.499738,0
18,0,0.0,0,1,6,291,40,25,0,1,1,0.389531,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.500161,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.512352,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.351493,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.244943,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.491962,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.262240,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.966560,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.912399,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.746598,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.023090,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.295647,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.076450,0

In [2]:
# importing pymysql to integrate python and sql
import pymysql

In [3]:
conn = pymysql.connect(database='predicted_outputs', user='root', password='NEWPASSWORD')

OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")